"""Helpers for building non-blocking merge risk advisory comments."""

from __future__ import annotations


HIGH_PRIORITY_HEADING = "High Priority"
EMPTY_FINDING_MARKERS = (
    "none",
    "none.",
    "no high priority issue",
    "no high-priority issue",
    "no high priority finding",
    "no high-priority finding",
    "no critical issue",
)


def _is_empty_finding_marker(text: str) -> bool:
    normalized = text.strip().lower().rstrip(".")
    return any(normalized == marker.rstrip(".") or normalized.startswith(marker) for marker in EMPTY_FINDING_MARKERS)


def parse_high_priority_findings(review_text: str) -> list[str]:
    """Extract bullet findings from the PR review High Priority section."""
    findings: list[str] = []
    in_high_priority_section = False
    current_finding: str | None = None

    for line in review_text.splitlines():
        stripped = line.strip()

        if stripped.startswith("#") and HIGH_PRIORITY_HEADING in stripped:
            in_high_priority_section = True
            current_finding = None
            continue

        if in_high_priority_section and stripped.startswith("#"):
            break

        if not in_high_priority_section:
            continue

        if not stripped or _is_empty_finding_marker(stripped):
            continue

        if stripped.startswith(("- ", "* ")):
            bullet_text = stripped[2:].strip()
            if _is_empty_finding_marker(bullet_text):
                current_finding = None
                continue
            if current_finding:
                findings.append(current_finding)
            current_finding = bullet_text
            continue

        if current_finding:
            current_finding = f"{current_finding} {stripped}"

    if current_finding:
        findings.append(current_finding)

    return findings


def build_advisory_comment(pr_title: str, pr_number: int, findings: list[str]) -> str:
    count = len(findings)
    bulleted_findings = "\n".join(f"- {finding}" for finding in findings)

    return f"""## ⚠️ Merge Risk Advisory — {pr_title} (#{pr_number})

The PR Reviewer flagged **{count} High priority issue(s)** in this PR.

**Recommendation:** Do not merge until the following are resolved:
{bulleted_findings}

**Options:**
- Fix the issues and push to this branch — review will re-run automatically
- Close this PR without merging to keep main clean
- Override and merge anyway (admin decision — your call)

This is a suggestion only. No action has been taken on this PR.

---
*Generated by ai-dev-productivity-kit Merge Risk Advisor. Humans decide. Always.*"""


def should_post_advisory(findings: list[str]) -> bool:
    return bool(findings)
